app:
  appName: app
  demoReplicaCount: 2
  tag: 1.0.8
  service:
    port: 8080
    targetPort: 5000
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m
ingress:
  dnsName: avshaproject.ddns.net
  enabled: true
mongodb:
  fullnameOverride: mongodb
  architecture: replicaset
  replicaCount: 3
  auth:
    rootUser: root
    rootPassword: example
