apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'git@github.com:HadadAvsha/Project-Gitops.git'
    targetRevision: HEAD
    path: Grade-app/
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
