elasticsearch:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    # limits:
    #   cpu: "500m"
    #   memory: "2Gi"

kibana:
  elasticsearchHosts: "http://elasticsearch-master:9200" #"http://elasticsearch-master:9200" #"http://elasticsearch-master-headless:9200"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    # limits:
    #   cpu: "500m"
    #   memory: "2Gi"
  ingress:
    enabled: false
    className: "nginx"
    pathtype: ImplementationSpecific
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: kibana-example.local
        paths:
          - path: /
    #tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local